### ISSUE TITLE
perms flag

### ISSUE THREAD

**Issue by mote166** [genboy/Festival#25]
the plugin doesn't respect the player's permission, for ex i set my perms to have a "example1" kit once i join a world , and put a command by festival in an area that teleports me to the world , so now i should get the "example1" kit but instead im getting the "example2" kit and even if i change my perms to have an other kit i just end up having "example2" kit and there are no errors in the console, if i use the command that teleports me to the world in the chat everything works as expected so the issue is from the plugin (even if i set perms flag to true and false the same result is given).

**Comment by genboy** [comment]
@mote166 
Humm, i'll check the code for sure but i have doubts this is a Festival bug.
Do i understand correctly that 
1. 'get kit example1' is a command set on the enter event of an area where you are teleported to, in one particular world
2. you were teleported to this particular world by a festival area tp command from an area in another world

If so, this involves so much more code then Festival alone. (as always with Festival :)
To solve this it might help to start double check the Festival configuration defaults and for both particular worlds, and also the specific perms for players in both the worlds.

For your info, there is no way the Festival plugin knows (yet) what player is doing the command or what perms the player has. 
**Wherever the command function originates from (pmmp/other plugin/festival itself), the comand execution is either done with temporary OP perms (default) or just with the player (command sender) perms, relying on the permissions set for the specific command** (apart from Festival).

Please do double check all concerning configurations, perm settings and other plugins involved, just to be sure.

There are at least 10 places to start debugging; 2 area perm flags + 3 configs + 1 'festival tp' + 1 'get kit' + 2 worlds perm setting + 2 plugins perm settings.
If a plugin relies on another plugin to manage the command permisions, this should be check too, in accoordance with both worlds and area configs and flags. 

That's a lot to check and partly not in my reach. 
Let me start by looking at my code and narrow down the propabillities of commands being executed with incorrect perms.

**Comment by mote166** [comment]
1- i have no such thing as world perms .
2- i have double checked all group perms, all groups have the perms they are supposed to have .
3- i use pureperms so the plugin should rely on it .
4- i have double checked if the perms flag is set to true or false it doesn't use the player's permission .
5- my current config:
```
# Config file for Festival

# Festival options
Options:
  
  # Messages (tip/pop) 
  Msgtype: pop
  
  # Messages persist display to ops (off/op/on)
  Msgdisplay: off

# Settings for unprotected areas in worlds without specific settings:
Default:

  # Keep players from getting hurt? 
  God: false

  # Keep players from editing the world?
  Edit: false 

  # Keep players from touching blocks and activating things like chests?
  Touch: false
  
  # Keep players from seeing enter/leave/description messages?
  Msg: true

  # Prevent players enter/leaving the area? Deny passage (previously barrier)
  Passage: false

  # Prevent players drop items in the area? Deny drop
  Drop: false

  # Player permission overwrite for area event command execution
  Perms: false

# Settings for unprotected areas in individual worlds:
Worlds:
 
  game1:

    # Keep players from getting hurt? 
    God: false 

    # Keep players from editing the world?
    Edit: false

    # Keep players from touching blocks and activating things like chests?
    Touch: false

    # Keep players from seeing enter/leave/description messages?
    Msg: true

    # Prevent players from enter/leaving the area? (previously barrier)
    Passage: false

    # Prevent players drop items in the area? Deny drop
    Drop: false

    # Player permission overwrite for area event command execution
    Perms: false

  World:
  
    # Keep players from getting hurt? 
    God: false

    # Keep players from editing the world?
    Edit: false

    # Keep players from touching blocks and activating things like chests?
    Touch: false

    # Keep players from seeing enter/leave/description messages?
    Msg: true

    # Prevent players from enter/leaving the area? (previously barrier)
    Passage: false

    # Prevent players drop items in the area? Deny drop
    Drop: false
 
    # Player permission overwrite for area event command execution
    Perms: false

```
